name: tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^17.1.0

  # API Request
  retrofit: ^4.9.2
  dio:

  # JSON serialization
  json_annotation: ^4.9.0

  # Debugging
  logger: ^2.6.2  # for logging purpose
  pretty_dio_logger: ^1.4.0
  
  # UI
  google_fonts: ^8.0.1
  cached_network_image: ^3.4.1
  lottie: ^3.3.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.2.3
  fluttertoast: ^9.0.0

  # iOS Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # DI
  injectable: ^2.7.1+4
  get_it:

  # Localization
  easy_localization: ^3.0.8

  # Local storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  equatable: ^2.0.8

  # Test
  bloc_test: ^10.0.0
  mockito: ^5.6.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  test: ^1.26.3
  pinput: ^6.0.2
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  image_picker: ^1.2.1
  http_parser: ^4.1.2
  country_picker: ^2.0.27 
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_messaging: ^16.1.2
  flutter_local_notifications: ^21.0.0
  firebase_database: ^12.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generation
  retrofit_generator: ^10.0.1
  build_runner: ^2.6.0
  injectable_generator:
  json_serializable: ^6.10.0
  flutter_gen_runner: ^5.9.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/lotties/
    - assets/images/

flutter_gen:
  output: lib/core/gen/
  integrations:
    lottie: true
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false