org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=192m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
android.useAndroidX=true
# Add this line to fix the "different roots" crash
kotlin.incremental=false